[workspace]
members = ["core", "archiver", "api"]
resolver = "3"

[workspace.package]
version = "0.2.0"
license = "MIT"
edition = "2024"

[workspace.dependencies]
apod-core = { path = "core" }

anyhow = "1.0.100"
chrono = { version = "0.4.42", features = ["serde"] }
chrono-tz = "0.10.4"
r2d2 = "0.8.10"
r2d2_sqlite = "0.31.0"
rusqlite = { version = "0.37.0", features = ["bundled", "chrono", "serde_json"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
thiserror = "2.0.18"
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread", "signal", "sync", "time"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[profile.release]
codegen-units = 1
lto = true
strip = true
