[package]
name = "apod-core"
version.workspace = true
license.workspace = true
edition.workspace = true

[features]
default = []
data = ["dep:sqlx"]
data-read = ["data", "dep:serde_json"]
data-write = ["data-read"]
sky = []
sky-data = ["sky", "data"]

[dependencies]
chrono = { workspace = true }
encoding_rs = "0.8.35"
regex = "1.13.1"
scraper = "0.27.0"
serde = { workspace = true }
serde_json = { workspace = true, optional = true }
sqlx = { workspace = true, optional = true }
thiserror = { workspace = true }
url = "2.5.8"

[dev-dependencies]
serde_json = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
