/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApodCredit: typeof import('./src/components/ApodCredit.vue')['default']
    Button: typeof import('primevue/button')['default']
    CalendarMonth: typeof import('./src/components/CalendarMonth.vue')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Drawer: typeof import('primevue/drawer')['default']
    EntryCard: typeof import('./src/components/EntryCard.vue')['default']
    EntryDetail: typeof import('./src/components/EntryDetail.vue')['default']
    EntryDiff: typeof import('./src/components/EntryDiff.vue')['default']
    EntryGrid: typeof import('./src/components/EntryGrid.vue')['default']
    EntrySkeleton: typeof import('./src/components/EntrySkeleton.vue')['default']
    ExternalLinkNotice: typeof import('./src/components/ExternalLinkNotice.vue')['default']
    FeedItem: typeof import('./src/components/FeedItem.vue')['default']
    GameBands: typeof import('./src/components/games/GameBands.vue')['default']
    GameOutcome: typeof import('./src/components/games/GameOutcome.vue')['default']
    GamePicture: typeof import('./src/components/games/GamePicture.vue')['default']
    GameRecord: typeof import('./src/components/games/GameRecord.vue')['default']
    GameReveal: typeof import('./src/components/games/GameReveal.vue')['default']
    GameShell: typeof import('./src/components/games/GameShell.vue')['default']
    GapDetail: typeof import('./src/components/GapDetail.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    Image: typeof import('primevue/image')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MediaFrame: typeof import('./src/components/MediaFrame.vue')['default']
    Message: typeof import('primevue/message')['default']
    MoonDial: typeof import('./src/components/MoonDial.vue')['default']
    Paginator: typeof import('primevue/paginator')['default']
    PictureTimeline: typeof import('./src/components/PictureTimeline.vue')['default']
    Popover: typeof import('primevue/popover')['default']
    RatingCard: typeof import('./src/components/rating/RatingCard.vue')['default']
    RatingDisclosure: typeof import('./src/components/rating/RatingDisclosure.vue')['default']
    RatingHelp: typeof import('./src/components/rating/RatingHelp.vue')['default']
    RatingOdds: typeof import('./src/components/rating/RatingOdds.vue')['default']
    RatingPicture: typeof import('./src/components/rating/RatingPicture.vue')['default']
    RatingProgress: typeof import('./src/components/rating/RatingProgress.vue')['default']
    ReadFilter: typeof import('./src/components/ReadFilter.vue')['default']
    ReadProgress: typeof import('./src/components/ReadProgress.vue')['default']
    RetryNotice: typeof import('./src/components/RetryNotice.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    SeriesChart: typeof import('./src/components/SeriesChart.vue')['default']
    SettingsDialog: typeof import('./src/components/SettingsDialog.vue')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    SkyPanels: typeof import('./src/components/SkyPanels.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    WelcomeNote: typeof import('./src/components/WelcomeNote.vue')['default']
    WordDetail: typeof import('./src/components/WordDetail.vue')['default']
    YearChart: typeof import('./src/components/YearChart.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
