/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    CalendarMonth: typeof import('./src/components/CalendarMonth.vue')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Drawer: typeof import('primevue/drawer')['default']
    EntryCard: typeof import('./src/components/EntryCard.vue')['default']
    EntryDetail: typeof import('./src/components/EntryDetail.vue')['default']
    EntryGrid: typeof import('./src/components/EntryGrid.vue')['default']
    EntrySkeleton: typeof import('./src/components/EntrySkeleton.vue')['default']
    ExternalLinkNotice: typeof import('./src/components/ExternalLinkNotice.vue')['default']
    FeedItem: typeof import('./src/components/FeedItem.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    Image: typeof import('primevue/image')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MediaFrame: typeof import('./src/components/MediaFrame.vue')['default']
    Message: typeof import('primevue/message')['default']
    Paginator: typeof import('primevue/paginator')['default']
    Popover: typeof import('primevue/popover')['default']
    ReadFilter: typeof import('./src/components/ReadFilter.vue')['default']
    ReadProgress: typeof import('./src/components/ReadProgress.vue')['default']
    RetryNotice: typeof import('./src/components/RetryNotice.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    SettingsDialog: typeof import('./src/components/SettingsDialog.vue')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    Tag: typeof import('primevue/tag')['default']
    Toast: typeof import('primevue/toast')['default']
    WordDetail: typeof import('./src/components/WordDetail.vue')['default']
    YearChart: typeof import('./src/components/YearChart.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
